server:
  port: 10000 #\u670D\u52A1\u7AEF\u53E3

spring:
  application:
    name: api-gateway #\u6307\u5B9A\u5E94\u7528\u540D
zuul:
  prefix: /api # 添加路由前缀
  host:
    connect-timeout-millis: 15000 #HTTP\u8FDE\u63A5\u8D85\u65F6\u5927\u4E8EHystrix\u7684\u8D85\u65F6\u65F6\u95F4
    socket-timeout-millis: 60000   #socket\u8D85\u65F6
  routes:
    user-service-provider: /user-server/** # \u8FD9\u91CC\u662F\u6620\u5C04\u8DEF\u5F84
ribbon:        #\u8BBE\u7F6Eribbon\u7684\u8D85\u65F6\u65F6\u95F4\u5C0F\u4E8Ezuul\u7684\u8D85\u65F6\u65F6\u95F4
  ReadTimeout: 10000
  ConnectTimeout: 10000
eureka:
  client:
    registry-fetch-interval-seconds: 5 # \u83B7\u53D6\u670D\u52A1\u5217\u8868\u7684\u5468\u671F\uFF1A5s
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}